# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Optional

from pydantic import Field as FieldInfo

from .._models import BaseModel
from .objective_context_window_data import ObjectiveContextWindowData

__all__ = ["ContextWindowCompacted"]


class ContextWindowCompacted(BaseModel):
    messages_compacted: Optional[int] = FieldInfo(alias="messagesCompacted", default=None)
    """Number of messages that were compacted"""

    new_context_window: Optional[ObjectiveContextWindowData] = FieldInfo(alias="newContextWindow", default=None)
    """The new context window created by this compaction"""

    strategies: Optional[List[str]] = None
    """The strategies that were applied during this compaction"""

    summary: Optional[str] = None
    """The summary generated by the summarization strategy, if used."""
