# Code generated by redwood. DO NOT EDIT.
from __future__ import annotations

import json
import os
from typing import Any, Mapping, Optional

import httpx

from . import types
from ._core import Core, decode_response
from ._webhooks import verify_webhook
from .resources import (
    Accounts,
    ApiKeys,
    WorkspaceAdmin,
    Profiles,
    Workspaces,
    Agents,
    AiProviderKeys,
    Models,
    MemoryLayers,
    Objectives,
    ToolSearch,
    Tenants,
    ToolSets,
    Uploads,
    WidgetSessions,
    Widgets,
    WorkspaceSecrets,
)


class Cadenya:
    """The Cadenya API client. Resource groups are attributes; unset
    options are read from the environment."""

    def __init__(
        self,
        *,
        api_key: Optional[str] = None,
        base_url: Optional[str] = None,
        webhook_secret: Optional[str] = None,
        http_client: Optional[httpx.Client] = None,
        max_retries: int = 0,
        workspace_id: Optional[str] = None,
    ) -> None:
        for _name, _value in (("api_key", api_key), ("base_url", base_url)):
            if _value is not None and not _value.strip():
                raise ValueError(f"{_name} must not be blank")
        api_key = api_key.strip() if api_key is not None else None
        base_url = base_url.strip() if base_url is not None else None
        if workspace_id is not None and not workspace_id.strip():
            raise ValueError("workspace_id must not be blank")
        workspace_id = workspace_id.strip() if workspace_id is not None else None
        api_key = api_key or os.environ.get("CADENYA_API_KEY", "").strip() or None
        if not api_key:
            raise ValueError("missing API key: pass api_key or set CADENYA_API_KEY")
        base_url = base_url or os.environ.get("CADENYA_BASE_URL", "").strip() or "https://api.cadenya.com"
        if webhook_secret is not None and not webhook_secret.strip():
            raise ValueError("webhook_secret must not be blank")
        webhook_secret = webhook_secret.strip() if webhook_secret is not None else None
        self._webhook_secret = webhook_secret or os.environ.get("CADENYA_WEBHOOK_SECRET", "").strip()
        defaults = {}
        defaults["workspaceId"] = workspace_id or os.environ.get("CADENYA_WORKSPACE_ID", "")
        core = Core(
            base_url=base_url,
            auth_header=("Authorization", "Bearer " + api_key),
            http_client=http_client,
            max_retries=max_retries,
            defaults=defaults,
            user_agent="cadenya-python/1.0.1 (api 1.0)",
        )
        self._core = core
        self.accounts = Accounts(core)
        self.api_keys = ApiKeys(core)
        self.workspace_admin = WorkspaceAdmin(core)
        self.profiles = Profiles(core)
        self.workspaces = Workspaces(core)
        self.agents = Agents(core)
        self.ai_provider_keys = AiProviderKeys(core)
        self.models = Models(core)
        self.memory_layers = MemoryLayers(core)
        self.objectives = Objectives(core)
        self.tool_search = ToolSearch(core)
        self.tenants = Tenants(core)
        self.tool_sets = ToolSets(core)
        self.uploads = Uploads(core)
        self.widget_sessions = WidgetSessions(core)
        self.widgets = Widgets(core)
        self.workspace_secrets = WorkspaceSecrets(core)

    def close(self) -> None:
        """Release the underlying HTTP transport (only if the client owns it)."""
        self._core.close()

    def __enter__(self) -> "Cadenya":
        return self

    def __exit__(self, *exc: Any) -> None:
        self.close()

    def unwrap_webhook(self, payload: bytes, headers: Mapping[str, str]) -> types.ObjectiveEventWebhookData:
        """Verify a Standard Webhooks delivery and return the typed payload."""
        if not self._webhook_secret:
            raise ValueError("missing webhook secret: pass webhook_secret or set CADENYA_WEBHOOK_SECRET")
        return unwrap_webhook(payload, headers, secret=self._webhook_secret)


def unwrap_webhook(
    payload: bytes, headers: Mapping[str, str], *, secret: str
) -> types.ObjectiveEventWebhookData:
    """Verify a Standard Webhooks delivery and return the typed payload,
    without constructing a client — webhook-only consumers need no API key."""
    if not secret:
        raise ValueError("missing webhook secret")
    verify_webhook(secret, payload, headers)
    return types.ObjectiveEventWebhookData._from_json(json.loads(payload))
