# Code generated by redwood. DO NOT EDIT.
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional, Union

from .. import types
from .._core import Core, RequestOptions, decode_response, parse_datetime, path_param
from .._pagination import SyncPage
from .._sse import Stream


class Accounts:
    def __init__(self, core: Core) -> None:
        self._core = core

    def retrieve(
        self,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> types.Account:
        """Retrieves the current account for the token accessing the API"""
        _path = "/v1/account"
        _data = self._core.request("GET", _path, request_options=request_options)
        return decode_response("accounts.retrieve", _data, lambda _d: types.Account._from_json(_d))

    def rotate_challenge_token(
        self,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> types.RotateChallengeTokenResponse:
        """Rotates the challenge token for the account"""
        _path = "/v1/account:rotateChallengeToken"
        _data = self._core.request("POST", _path, request_options=request_options)
        return decode_response("accounts.rotate_challenge_token", _data, lambda _d: types.RotateChallengeTokenResponse._from_json(_d))

    def rotate_webhook_signing_key(
        self,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> types.RotateWebhookEventsHmacSecretResponse:
        """Rotates the webhook signing key for the account"""
        _path = "/v1/account:rotateWebhookSigningKey"
        _data = self._core.request("POST", _path, request_options=request_options)
        return decode_response("accounts.rotate_webhook_signing_key", _data, lambda _d: types.RotateWebhookEventsHmacSecretResponse._from_json(_d))
