# Code generated by redwood. DO NOT EDIT.
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional, Union

from .. import types
from .._core import Core, RequestOptions, decode_response, parse_datetime, path_param
from .._pagination import SyncPage
from .._sse import Stream


class AgentVariations:
    def __init__(self, core: Core) -> None:
        self._core = core

    def list(
        self,
        agent_id: str,
        *,
        workspace_id: Optional[str] = None,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        sort_order: Optional[str] = None,
        include_info: Optional[bool] = None,
        labels: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[types.AgentVariation]:
        """List variations"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/agents/{path_param('agentId', agent_id)}/variations"
        _query = {
            "limit": limit,
            "cursor": cursor,
            "sortOrder": sort_order,
            "includeInfo": include_info,
            "labels": labels,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options) or {}
        _items = decode_response("agents.variations.list", _data, lambda _d: [types.AgentVariation._from_json(item) for item in (_d.get("items") or [])])
        _next_cursor = (((_data).get("pagination") or {})).get("nextCursor") or ""

        def _fetch(_cursor: str) -> SyncPage[types.AgentVariation]:
            return self.list(agent_id, workspace_id=workspace_id, limit=limit, cursor=_cursor, sort_order=sort_order, include_info=include_info, labels=labels, request_options=request_options)

        return SyncPage(_items, _next_cursor, _fetch)

    def create(
        self,
        agent_id: str,
        *,
        metadata: types.CreateResourceMetadataParam,
        spec: types.AgentVariationSpecParam,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.AgentVariation:
        """Create a new variation"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/agents/{path_param('agentId', agent_id)}/variations"
        _body = {
            "metadata": (lambda _v: types._encode_CreateResourceMetadata(_v))(metadata),
            "spec": (lambda _v: types._encode_AgentVariationSpec(_v))(spec),
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("POST", _path, body=_body, request_options=request_options)
        return decode_response("agents.variations.create", _data, lambda _d: types.AgentVariation._from_json(_d))

    def retrieve(
        self,
        agent_id: str,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.AgentVariation:
        """Get a variation by ID"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/agents/{path_param('agentId', agent_id)}/variations/{path_param('id', id)}"
        _data = self._core.request("GET", _path, request_options=request_options)
        return decode_response("agents.variations.retrieve", _data, lambda _d: types.AgentVariation._from_json(_d))

    def delete(
        self,
        agent_id: str,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> None:
        """Delete a variation"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/agents/{path_param('agentId', agent_id)}/variations/{path_param('id', id)}"
        self._core.request("DELETE", _path, expects_body=False, request_options=request_options)
        return None

    def update(
        self,
        agent_id: str,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        metadata: Optional[types.UpdateResourceMetadataParam] = None,
        spec: Optional[types.AgentVariationSpecParam] = None,
        update_mask: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.AgentVariation:
        """Update a variation"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/agents/{path_param('agentId', agent_id)}/variations/{path_param('id', id)}"
        _body = {
            "metadata": (lambda _v: types._encode_UpdateResourceMetadata(_v))(metadata),
            "spec": (lambda _v: types._encode_AgentVariationSpec(_v))(spec),
            "updateMask": update_mask,
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("PATCH", _path, body=_body, request_options=request_options)
        return decode_response("agents.variations.update", _data, lambda _d: types.AgentVariation._from_json(_d))

    def add_assignment(
        self,
        agent_id: str,
        variation_id: str,
        *,
        body: types.AddAgentVariationAssignmentRequestParam,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.VariationAssignment:
        """Add an assignment to a variation"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/agents/{path_param('agentId', agent_id)}/variations/{path_param('variationId', variation_id)}/assignments"
        _data = self._core.request("POST", _path, body=(lambda _v: types._encode_AddAgentVariationAssignmentRequest(_v))(body), request_options=request_options)
        return decode_response("agents.variations.add_assignment", _data, lambda _d: types._decode_VariationAssignment(_d))

    def remove_assignment(
        self,
        agent_id: str,
        variation_id: str,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> None:
        """Remove an assignment from a variation"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/agents/{path_param('agentId', agent_id)}/variations/{path_param('variationId', variation_id)}/assignments/{path_param('id', id)}"
        self._core.request("DELETE", _path, expects_body=False, request_options=request_options)
        return None

    def add_memory_layer(
        self,
        agent_id: str,
        variation_id: str,
        *,
        memory_layer_id: str,
        workspace_id: Optional[str] = None,
        position: Optional[int] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.VariationMemoryLayerAssignment:
        """Attach a memory layer to a variation"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/agents/{path_param('agentId', agent_id)}/variations/{path_param('variationId', variation_id)}/memory_layer_assignments"
        _body = {
            "memoryLayerId": memory_layer_id,
            "position": position,
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("POST", _path, body=_body, request_options=request_options)
        return decode_response("agents.variations.add_memory_layer", _data, lambda _d: types.VariationMemoryLayerAssignment._from_json(_d))

    def remove_memory_layer(
        self,
        agent_id: str,
        variation_id: str,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> None:
        """Remove a memory layer assignment from a variation"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/agents/{path_param('agentId', agent_id)}/variations/{path_param('variationId', variation_id)}/memory_layer_assignments/{path_param('id', id)}"
        self._core.request("DELETE", _path, expects_body=False, request_options=request_options)
        return None

    def update_memory_layer(
        self,
        agent_id: str,
        variation_id: str,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        position: Optional[int] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.VariationMemoryLayerAssignment:
        """Update a variation's memory layer assignment"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/agents/{path_param('agentId', agent_id)}/variations/{path_param('variationId', variation_id)}/memory_layer_assignments/{path_param('id', id)}"
        _body = {
            "position": position,
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("PATCH", _path, body=_body, request_options=request_options)
        return decode_response("agents.variations.update_memory_layer", _data, lambda _d: types.VariationMemoryLayerAssignment._from_json(_d))
