# Code generated by redwood. DO NOT EDIT.
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional, Union

from .. import types
from .._core import Core, RequestOptions, decode_response, parse_datetime, path_param
from .._pagination import SyncPage
from .._sse import Stream


from .agent_schedules import AgentSchedules
from .agent_variations import AgentVariations

class Agents:
    def __init__(self, core: Core) -> None:
        self._core = core
        self.schedules = AgentSchedules(core)
        self.variations = AgentVariations(core)

    def list(
        self,
        *,
        workspace_id: Optional[str] = None,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        prefix: Optional[str] = None,
        query: Optional[str] = None,
        state: Optional[types.AgentServiceListAgentsState] = None,
        variation_selection_mode: Optional[types.AgentServiceListAgentsVariationSelectionMode] = None,
        labels: Optional[str] = None,
        sort_order: Optional[str] = None,
        include_info: Optional[bool] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[types.Agent]:
        """List agents"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/agents"
        _query = {
            "limit": limit,
            "cursor": cursor,
            "prefix": prefix,
            "query": query,
            "state": state,
            "variationSelectionMode": variation_selection_mode,
            "labels": labels,
            "sortOrder": sort_order,
            "includeInfo": include_info,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options) or {}
        _items = decode_response("agents.list", _data, lambda _d: [types.Agent._from_json(item) for item in (_d.get("items") or [])])
        _next_cursor = (((_data).get("pagination") or {})).get("nextCursor") or ""

        def _fetch(_cursor: str) -> SyncPage[types.Agent]:
            return self.list(workspace_id=workspace_id, limit=limit, cursor=_cursor, prefix=prefix, query=query, state=state, variation_selection_mode=variation_selection_mode, labels=labels, sort_order=sort_order, include_info=include_info, request_options=request_options)

        return SyncPage(_items, _next_cursor, _fetch)

    def create(
        self,
        *,
        metadata: types.CreateResourceMetadataParam,
        spec: types.AgentSpecParam,
        workspace_id: Optional[str] = None,
        default_variation: Optional[types.CreateAgentVariationRequestParam] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.Agent:
        """Create a new agent"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/agents"
        _body = {
            "metadata": (lambda _v: types._encode_CreateResourceMetadata(_v))(metadata),
            "spec": (lambda _v: types._encode_AgentSpec(_v))(spec),
            "defaultVariation": (lambda _v: types._encode_CreateAgentVariationRequest(_v))(default_variation),
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("POST", _path, body=_body, request_options=request_options)
        return decode_response("agents.create", _data, lambda _d: types.Agent._from_json(_d))

    def list_feedback(
        self,
        agent_id: str,
        *,
        workspace_id: Optional[str] = None,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        query: Optional[str] = None,
        sentiment: Optional[types.AgentServiceListAgentFeedbackSentiment] = None,
        agent_variation_id: Optional[str] = None,
        created_after: Optional[Union[str, datetime]] = None,
        created_before: Optional[Union[str, datetime]] = None,
        labels: Optional[str] = None,
        include_info: Optional[bool] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[types.ObjectiveFeedback]:
        """List feedback for an agent"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/agents/{path_param('agentId', agent_id)}/feedback"
        _query = {
            "limit": limit,
            "cursor": cursor,
            "query": query,
            "sentiment": sentiment,
            "agentVariationId": agent_variation_id,
            "createdAfter": created_after,
            "createdBefore": created_before,
            "labels": labels,
            "includeInfo": include_info,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options) or {}
        _items = decode_response("agents.list_feedback", _data, lambda _d: [types.ObjectiveFeedback._from_json(item) for item in (_d.get("items") or [])])
        _next_cursor = (((_data).get("pagination") or {})).get("nextCursor") or ""

        def _fetch(_cursor: str) -> SyncPage[types.ObjectiveFeedback]:
            return self.list_feedback(agent_id, workspace_id=workspace_id, limit=limit, cursor=_cursor, query=query, sentiment=sentiment, agent_variation_id=agent_variation_id, created_after=created_after, created_before=created_before, labels=labels, include_info=include_info, request_options=request_options)

        return SyncPage(_items, _next_cursor, _fetch)

    def list_webhook_deliveries(
        self,
        agent_id: str,
        *,
        workspace_id: Optional[str] = None,
        cursor: Optional[str] = None,
        limit: Optional[int] = None,
        objective_id: Optional[str] = None,
        event_type: Optional[types.AgentServiceListAgentWebhookDeliveriesEventType] = None,
        labels: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[types.WebhookDelivery]:
        """List webhook deliveries"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/agents/{path_param('agentId', agent_id)}/webhook_deliveries"
        _query = {
            "cursor": cursor,
            "limit": limit,
            "objectiveId": objective_id,
            "eventType": event_type,
            "labels": labels,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options) or {}
        _items = decode_response("agents.list_webhook_deliveries", _data, lambda _d: [types.WebhookDelivery._from_json(item) for item in (_d.get("items") or [])])
        _next_cursor = (((_data).get("pagination") or {})).get("nextCursor") or ""

        def _fetch(_cursor: str) -> SyncPage[types.WebhookDelivery]:
            return self.list_webhook_deliveries(agent_id, workspace_id=workspace_id, cursor=_cursor, limit=limit, objective_id=objective_id, event_type=event_type, labels=labels, request_options=request_options)

        return SyncPage(_items, _next_cursor, _fetch)

    def retrieve(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.Agent:
        """Get an agent by ID"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/agents/{path_param('id', id)}"
        _data = self._core.request("GET", _path, request_options=request_options)
        return decode_response("agents.retrieve", _data, lambda _d: types.Agent._from_json(_d))

    def delete(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> None:
        """Delete an agent"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/agents/{path_param('id', id)}"
        self._core.request("DELETE", _path, expects_body=False, request_options=request_options)
        return None

    def update(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        metadata: Optional[types.UpdateResourceMetadataParam] = None,
        spec: Optional[types.AgentSpecParam] = None,
        update_mask: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.Agent:
        """Update an agent"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/agents/{path_param('id', id)}"
        _body = {
            "metadata": (lambda _v: types._encode_UpdateResourceMetadata(_v))(metadata),
            "spec": (lambda _v: types._encode_AgentSpec(_v))(spec),
            "updateMask": update_mask,
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("PATCH", _path, body=_body, request_options=request_options)
        return decode_response("agents.update", _data, lambda _d: types.Agent._from_json(_d))

    def archive(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.Agent:
        """Archive an agent"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/agents/{path_param('id', id)}:archive"
        _data = self._core.request("POST", _path, request_options=request_options)
        return decode_response("agents.archive", _data, lambda _d: types.Agent._from_json(_d))

    def publish(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.Agent:
        """Publish an agent"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/agents/{path_param('id', id)}:publish"
        _data = self._core.request("POST", _path, request_options=request_options)
        return decode_response("agents.publish", _data, lambda _d: types.Agent._from_json(_d))

    def unarchive(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.Agent:
        """Unarchive an agent"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/agents/{path_param('id', id)}:unarchive"
        _data = self._core.request("POST", _path, request_options=request_options)
        return decode_response("agents.unarchive", _data, lambda _d: types.Agent._from_json(_d))

    def unpublish(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.Agent:
        """Unpublish an agent"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/agents/{path_param('id', id)}:unpublish"
        _data = self._core.request("POST", _path, request_options=request_options)
        return decode_response("agents.unpublish", _data, lambda _d: types.Agent._from_json(_d))
