# Code generated by redwood. DO NOT EDIT.
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional, Union

from .. import types
from .._core import Core, RequestOptions, decode_response, parse_datetime, path_param
from .._pagination import SyncPage
from .._sse import Stream


class ApiKeys:
    def __init__(self, core: Core) -> None:
        self._core = core

    def retrieve_global(
        self,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> types.APIKey:
        """Get the global API key"""
        _path = "/v1/account/global_api_key"
        _data = self._core.request("GET", _path, request_options=request_options)
        return decode_response("api_keys.retrieve_global", _data, lambda _d: types.APIKey._from_json(_d))

    def disable_global(
        self,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> types.APIKey:
        """Disable the global API key"""
        _path = "/v1/account/global_api_key:disable"
        _data = self._core.request("POST", _path, request_options=request_options)
        return decode_response("api_keys.disable_global", _data, lambda _d: types.APIKey._from_json(_d))

    def enable_global(
        self,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> types.APIKey:
        """Enable the global API key"""
        _path = "/v1/account/global_api_key:enable"
        _data = self._core.request("POST", _path, request_options=request_options)
        return decode_response("api_keys.enable_global", _data, lambda _d: types.APIKey._from_json(_d))

    def rotate_global(
        self,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> types.APIKey:
        """Rotate the global API key"""
        _path = "/v1/account/global_api_key:rotate"
        _data = self._core.request("POST", _path, request_options=request_options)
        return decode_response("api_keys.rotate_global", _data, lambda _d: types.APIKey._from_json(_d))

    def list(
        self,
        *,
        workspace_id: Optional[str] = None,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        prefix: Optional[str] = None,
        query: Optional[str] = None,
        labels: Optional[str] = None,
        sort_order: Optional[str] = None,
        include_info: Optional[bool] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[types.APIKey]:
        """List API keys"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/api_keys"
        _query = {
            "limit": limit,
            "cursor": cursor,
            "prefix": prefix,
            "query": query,
            "labels": labels,
            "sortOrder": sort_order,
            "includeInfo": include_info,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options) or {}
        _items = decode_response("api_keys.list", _data, lambda _d: [types.APIKey._from_json(item) for item in (_d.get("items") or [])])
        _next_cursor = (((_data).get("pagination") or {})).get("nextCursor") or ""

        def _fetch(_cursor: str) -> SyncPage[types.APIKey]:
            return self.list(workspace_id=workspace_id, limit=limit, cursor=_cursor, prefix=prefix, query=query, labels=labels, sort_order=sort_order, include_info=include_info, request_options=request_options)

        return SyncPage(_items, _next_cursor, _fetch)

    def create(
        self,
        *,
        metadata: types.CreateAccountResourceMetadataParam,
        spec: types.APIKeySpecParam,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.APIKey:
        """Create a new API key"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/api_keys"
        _body = {
            "metadata": (lambda _v: types._encode_CreateAccountResourceMetadata(_v))(metadata),
            "spec": (lambda _v: types._encode_APIKeySpec(_v))(spec),
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("POST", _path, body=_body, request_options=request_options)
        return decode_response("api_keys.create", _data, lambda _d: types.APIKey._from_json(_d))

    def retrieve(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.APIKey:
        """Get an API key by ID"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/api_keys/{path_param('id', id)}"
        _data = self._core.request("GET", _path, request_options=request_options)
        return decode_response("api_keys.retrieve", _data, lambda _d: types.APIKey._from_json(_d))

    def delete(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> None:
        """Delete an API key"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/api_keys/{path_param('id', id)}"
        self._core.request("DELETE", _path, expects_body=False, request_options=request_options)
        return None

    def update(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        metadata: Optional[types.UpdateAccountResourceMetadataParam] = None,
        spec: Optional[types.APIKeySpecParam] = None,
        update_mask: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.APIKey:
        """Update an API key"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/api_keys/{path_param('id', id)}"
        _body = {
            "metadata": (lambda _v: types._encode_UpdateAccountResourceMetadata(_v))(metadata),
            "spec": (lambda _v: types._encode_APIKeySpec(_v))(spec),
            "updateMask": update_mask,
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("PATCH", _path, body=_body, request_options=request_options)
        return decode_response("api_keys.update", _data, lambda _d: types.APIKey._from_json(_d))

    def disable(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.APIKey:
        """Disable an API key"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/api_keys/{path_param('id', id)}:disable"
        _data = self._core.request("POST", _path, request_options=request_options)
        return decode_response("api_keys.disable", _data, lambda _d: types.APIKey._from_json(_d))

    def enable(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.APIKey:
        """Enable an API key"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/api_keys/{path_param('id', id)}:enable"
        _data = self._core.request("POST", _path, request_options=request_options)
        return decode_response("api_keys.enable", _data, lambda _d: types.APIKey._from_json(_d))

    def rotate(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.APIKey:
        """Rotate an API key"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/api_keys/{path_param('id', id)}:rotate"
        _data = self._core.request("POST", _path, request_options=request_options)
        return decode_response("api_keys.rotate", _data, lambda _d: types.APIKey._from_json(_d))
