# Code generated by redwood. DO NOT EDIT.
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional, Union

from .. import types
from .._core import Core, RequestOptions, decode_response, parse_datetime, path_param
from .._pagination import SyncPage
from .._sse import Stream


class Models:
    def __init__(self, core: Core) -> None:
        self._core = core

    def list(
        self,
        *,
        workspace_id: Optional[str] = None,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        prefix: Optional[str] = None,
        query: Optional[str] = None,
        state: Optional[types.ModelServiceListModelsState] = None,
        ai_provider_key_id: Optional[str] = None,
        is_assigned: Optional[bool] = None,
        labels: Optional[str] = None,
        sort_order: Optional[str] = None,
        include_info: Optional[bool] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[types.Model]:
        """List models"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/models"
        _query = {
            "limit": limit,
            "cursor": cursor,
            "prefix": prefix,
            "query": query,
            "state": state,
            "aiProviderKeyId": ai_provider_key_id,
            "isAssigned": is_assigned,
            "labels": labels,
            "sortOrder": sort_order,
            "includeInfo": include_info,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options) or {}
        _items = decode_response("models.list", _data, lambda _d: [types.Model._from_json(item) for item in (_d.get("items") or [])])
        _next_cursor = (((_data).get("pagination") or {})).get("nextCursor") or ""

        def _fetch(_cursor: str) -> SyncPage[types.Model]:
            return self.list(workspace_id=workspace_id, limit=limit, cursor=_cursor, prefix=prefix, query=query, state=state, ai_provider_key_id=ai_provider_key_id, is_assigned=is_assigned, labels=labels, sort_order=sort_order, include_info=include_info, request_options=request_options)

        return SyncPage(_items, _next_cursor, _fetch)

    def retrieve(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.Model:
        """Get a model by ID"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/models/{path_param('id', id)}"
        _data = self._core.request("GET", _path, request_options=request_options)
        return decode_response("models.retrieve", _data, lambda _d: types.Model._from_json(_d))

    def disable(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.Model:
        """Disable a model"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/models/{path_param('id', id)}:disable"
        _data = self._core.request("POST", _path, request_options=request_options)
        return decode_response("models.disable", _data, lambda _d: types.Model._from_json(_d))

    def enable(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.Model:
        """Enable a model"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/models/{path_param('id', id)}:enable"
        _data = self._core.request("POST", _path, request_options=request_options)
        return decode_response("models.enable", _data, lambda _d: types.Model._from_json(_d))

    def swap_on_variations(
        self,
        *,
        workspace_id: Optional[str] = None,
        model_swaps: Optional[List[types.SwapModelOnVariationsRequest_ModelSwapParam]] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> None:
        """Swap models on agent variations"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/models:swapModelOnVariations"
        _body = {
            "modelSwaps": (lambda _v: [((lambda _v: types._encode_SwapModelOnVariationsRequest_ModelSwap(_v)))(_i) for _i in _v] if isinstance(_v, list) else _v)(model_swaps),
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        self._core.request("POST", _path, body=_body, expects_body=False, request_options=request_options)
        return None
