# Code generated by redwood. DO NOT EDIT.
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional, Union

from .. import types
from .._core import Core, RequestOptions, decode_response, parse_datetime, path_param
from .._pagination import SyncPage
from .._sse import Stream


class Objectives:
    def __init__(self, core: Core) -> None:
        self._core = core

    def list(
        self,
        *,
        workspace_id: Optional[str] = None,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        agent_id: Optional[str] = None,
        parent_objective_id: Optional[str] = None,
        state: Optional[types.ObjectiveServiceListObjectivesState] = None,
        profile_id: Optional[str] = None,
        sort_order: Optional[str] = None,
        include_info: Optional[bool] = None,
        agent_schedule_id: Optional[str] = None,
        labels: Optional[str] = None,
        tenant_id: Optional[str] = None,
        subject_id: Optional[str] = None,
        widget_id: Optional[str] = None,
        widget_session_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[types.Objective]:
        """List objectives"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/objectives"
        _query = {
            "limit": limit,
            "cursor": cursor,
            "agentId": agent_id,
            "parentObjectiveId": parent_objective_id,
            "state": state,
            "profileId": profile_id,
            "sortOrder": sort_order,
            "includeInfo": include_info,
            "agentScheduleId": agent_schedule_id,
            "labels": labels,
            "tenantId": tenant_id,
            "subjectId": subject_id,
            "widgetId": widget_id,
            "widgetSessionId": widget_session_id,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options) or {}
        _items = decode_response("objectives.list", _data, lambda _d: [types.Objective._from_json(item) for item in (_d.get("items") or [])])
        _next_cursor = (((_data).get("pagination") or {})).get("nextCursor") or ""

        def _fetch(_cursor: str) -> SyncPage[types.Objective]:
            return self.list(workspace_id=workspace_id, limit=limit, cursor=_cursor, agent_id=agent_id, parent_objective_id=parent_objective_id, state=state, profile_id=profile_id, sort_order=sort_order, include_info=include_info, agent_schedule_id=agent_schedule_id, labels=labels, tenant_id=tenant_id, subject_id=subject_id, widget_id=widget_id, widget_session_id=widget_session_id, request_options=request_options)

        return SyncPage(_items, _next_cursor, _fetch)

    def create(
        self,
        *,
        agent_id: str,
        system_prompt_data: Dict[str, Any],
        workspace_id: Optional[str] = None,
        variation_id: Optional[str] = None,
        metadata: Optional[types.CreateOperationMetadataParam] = None,
        first_user_message: Optional[str] = None,
        secrets: Optional[List[types.CreateObjectiveRequest_SecretParam]] = None,
        memory_cascade: Optional[List[types.MemoryReferenceParam]] = None,
        first_user_message_data: Optional[Dict[str, Any]] = None,
        episodic_memory: Optional[types.ObjectiveEpisodicConfigParam] = None,
        tenant: Optional[types.TenantAssertionParam] = None,
        subject: Optional[types.SubjectAssertionParam] = None,
        pinned_parameters: Optional[Dict[str, str]] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.Objective:
        """Create a new objective"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/objectives"
        _body = {
            "agentId": agent_id,
            "variationId": variation_id,
            "metadata": (lambda _v: types._encode_CreateOperationMetadata(_v))(metadata),
            "systemPromptData": system_prompt_data,
            "firstUserMessage": first_user_message,
            "secrets": (lambda _v: [((lambda _v: types._encode_CreateObjectiveRequest_Secret(_v)))(_i) for _i in _v] if isinstance(_v, list) else _v)(secrets),
            "memoryCascade": (lambda _v: [((lambda _v: types._encode_MemoryReference(_v)))(_i) for _i in _v] if isinstance(_v, list) else _v)(memory_cascade),
            "firstUserMessageData": first_user_message_data,
            "episodicMemory": (lambda _v: types._encode_ObjectiveEpisodicConfig(_v))(episodic_memory),
            "tenant": (lambda _v: types._encode_TenantAssertion(_v))(tenant),
            "subject": (lambda _v: types._encode_SubjectAssertion(_v))(subject),
            "pinnedParameters": pinned_parameters,
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("POST", _path, body=_body, request_options=request_options)
        return decode_response("objectives.create", _data, lambda _d: types.Objective._from_json(_d))

    def retrieve(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.Objective:
        """Get an objective by ID"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/objectives/{path_param('id', id)}"
        _data = self._core.request("GET", _path, request_options=request_options)
        return decode_response("objectives.retrieve", _data, lambda _d: types.Objective._from_json(_d))

    def list_context_windows(
        self,
        objective_id: str,
        *,
        workspace_id: Optional[str] = None,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        include_info: Optional[bool] = None,
        labels: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[types.ObjectiveContextWindow]:
        """List objective context windows"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/objectives/{path_param('objectiveId', objective_id)}/context_windows"
        _query = {
            "limit": limit,
            "cursor": cursor,
            "includeInfo": include_info,
            "labels": labels,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options) or {}
        _items = decode_response("objectives.list_context_windows", _data, lambda _d: [types.ObjectiveContextWindow._from_json(item) for item in (_d.get("items") or [])])
        _next_cursor = (((_data).get("pagination") or {})).get("nextCursor") or ""

        def _fetch(_cursor: str) -> SyncPage[types.ObjectiveContextWindow]:
            return self.list_context_windows(objective_id, workspace_id=workspace_id, limit=limit, cursor=_cursor, include_info=include_info, labels=labels, request_options=request_options)

        return SyncPage(_items, _next_cursor, _fetch)

    def retrieve_diagnostics(
        self,
        objective_id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.GetObjectiveDiagnosticsResponse:
        """Get objective context diagnostics"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/objectives/{path_param('objectiveId', objective_id)}/diagnostics"
        _data = self._core.request("GET", _path, request_options=request_options)
        return decode_response("objectives.retrieve_diagnostics", _data, lambda _d: types.GetObjectiveDiagnosticsResponse._from_json(_d))

    def list_events(
        self,
        objective_id: str,
        *,
        workspace_id: Optional[str] = None,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        sort_order: Optional[str] = None,
        include_info: Optional[bool] = None,
        window_id: Optional[str] = None,
        since_event_id: Optional[str] = None,
        labels: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[types.ObjectiveEvent]:
        """List objective events"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/objectives/{path_param('objectiveId', objective_id)}/events"
        _query = {
            "limit": limit,
            "cursor": cursor,
            "sortOrder": sort_order,
            "includeInfo": include_info,
            "windowId": window_id,
            "sinceEventId": since_event_id,
            "labels": labels,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options) or {}
        _items = decode_response("objectives.list_events", _data, lambda _d: [types.ObjectiveEvent._from_json(item) for item in (_d.get("items") or [])])
        _next_cursor = (((_data).get("pagination") or {})).get("nextCursor") or ""

        def _fetch(_cursor: str) -> SyncPage[types.ObjectiveEvent]:
            return self.list_events(objective_id, workspace_id=workspace_id, limit=limit, cursor=_cursor, sort_order=sort_order, include_info=include_info, window_id=window_id, since_event_id=since_event_id, labels=labels, request_options=request_options)

        return SyncPage(_items, _next_cursor, _fetch)

    def stream_events(
        self,
        objective_id: str,
        *,
        workspace_id: Optional[str] = None,
        last_event_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> Stream[types.ObjectiveEvent]:
        """Stream objective events"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/objectives/{path_param('objectiveId', objective_id)}/events:stream"
        _headers = {"Last-Event-ID": last_event_id} if last_event_id else None
        _response = self._core.raw("GET", _path, headers=_headers, request_options=request_options)
        _reconnect = None if (request_options is not None and request_options.reconnect is False) else (lambda _rid: self._core.raw("GET", _path, headers=({"Last-Event-ID": _rid} if _rid else None), request_options=request_options))
        return Stream(_response, lambda event: decode_response("objectives.stream_events", event, lambda _d: types.ObjectiveEvent._from_json(_d)), last_event_id=last_event_id, skip_events=("ping", "open",), reconnect=_reconnect)

    def list_feedback(
        self,
        objective_id: str,
        *,
        workspace_id: Optional[str] = None,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        labels: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[types.ObjectiveFeedback]:
        """List feedback for an objective"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/objectives/{path_param('objectiveId', objective_id)}/feedback"
        _query = {
            "limit": limit,
            "cursor": cursor,
            "labels": labels,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options) or {}
        _items = decode_response("objectives.list_feedback", _data, lambda _d: [types.ObjectiveFeedback._from_json(item) for item in (_d.get("items") or [])])
        _next_cursor = (((_data).get("pagination") or {})).get("nextCursor") or ""

        def _fetch(_cursor: str) -> SyncPage[types.ObjectiveFeedback]:
            return self.list_feedback(objective_id, workspace_id=workspace_id, limit=limit, cursor=_cursor, labels=labels, request_options=request_options)

        return SyncPage(_items, _next_cursor, _fetch)

    def create_feedback(
        self,
        objective_id: str,
        *,
        metadata: types.CreateOperationMetadataParam,
        data: types.ObjectiveFeedbackDataParam,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.ObjectiveFeedback:
        """Submit feedback for an objective"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/objectives/{path_param('objectiveId', objective_id)}/feedback"
        _body = {
            "metadata": (lambda _v: types._encode_CreateOperationMetadata(_v))(metadata),
            "data": (lambda _v: types._encode_ObjectiveFeedbackData(_v))(data),
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("POST", _path, body=_body, request_options=request_options)
        return decode_response("objectives.create_feedback", _data, lambda _d: types.ObjectiveFeedback._from_json(_d))

    def list_tasks(
        self,
        objective_id: str,
        *,
        workspace_id: Optional[str] = None,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        sort_order: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[types.ObjectiveTask]:
        """List objective tasks"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/objectives/{path_param('objectiveId', objective_id)}/tasks"
        _query = {
            "limit": limit,
            "cursor": cursor,
            "sortOrder": sort_order,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options) or {}
        _items = decode_response("objectives.list_tasks", _data, lambda _d: [types.ObjectiveTask._from_json(item) for item in (_d.get("items") or [])])
        _next_cursor = (((_data).get("pagination") or {})).get("nextCursor") or ""

        def _fetch(_cursor: str) -> SyncPage[types.ObjectiveTask]:
            return self.list_tasks(objective_id, workspace_id=workspace_id, limit=limit, cursor=_cursor, sort_order=sort_order, request_options=request_options)

        return SyncPage(_items, _next_cursor, _fetch)

    def retrieve_task(
        self,
        objective_id: str,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.ObjectiveTask:
        """Get an objective task by ID"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/objectives/{path_param('objectiveId', objective_id)}/tasks/{path_param('id', id)}"
        _data = self._core.request("GET", _path, request_options=request_options)
        return decode_response("objectives.retrieve_task", _data, lambda _d: types.ObjectiveTask._from_json(_d))

    def list_tool_calls(
        self,
        objective_id: str,
        *,
        workspace_id: Optional[str] = None,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        status: Optional[types.ObjectiveServiceListObjectiveToolCallsStatus] = None,
        include_info: Optional[bool] = None,
        execution_status: Optional[types.ObjectiveServiceListObjectiveToolCallsExecutionStatus] = None,
        labels: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[types.ObjectiveToolCall]:
        """List objective tool calls"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/objectives/{path_param('objectiveId', objective_id)}/tool_calls"
        _query = {
            "limit": limit,
            "cursor": cursor,
            "status": status,
            "includeInfo": include_info,
            "executionStatus": execution_status,
            "labels": labels,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options) or {}
        _items = decode_response("objectives.list_tool_calls", _data, lambda _d: [types.ObjectiveToolCall._from_json(item) for item in (_d.get("items") or [])])
        _next_cursor = (((_data).get("pagination") or {})).get("nextCursor") or ""

        def _fetch(_cursor: str) -> SyncPage[types.ObjectiveToolCall]:
            return self.list_tool_calls(objective_id, workspace_id=workspace_id, limit=limit, cursor=_cursor, status=status, include_info=include_info, execution_status=execution_status, labels=labels, request_options=request_options)

        return SyncPage(_items, _next_cursor, _fetch)

    def retrieve_tool_call(
        self,
        objective_id: str,
        tool_call_id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.ObjectiveToolCallWithResult:
        """Get an objective tool call by ID"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/objectives/{path_param('objectiveId', objective_id)}/tool_calls/{path_param('toolCallId', tool_call_id)}"
        _data = self._core.request("GET", _path, request_options=request_options)
        return decode_response("objectives.retrieve_tool_call", _data, lambda _d: types.ObjectiveToolCallWithResult._from_json(_d))

    def approve_tool_call(
        self,
        objective_id: str,
        tool_call_id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.ObjectiveToolCall:
        """Approve a tool call"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/objectives/{path_param('objectiveId', objective_id)}/tool_calls/{path_param('toolCallId', tool_call_id)}:approve"
        _data = self._core.request("POST", _path, request_options=request_options)
        return decode_response("objectives.approve_tool_call", _data, lambda _d: types.ObjectiveToolCall._from_json(_d))

    def deny_tool_call(
        self,
        objective_id: str,
        tool_call_id: str,
        *,
        workspace_id: Optional[str] = None,
        memo: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.ObjectiveToolCall:
        """Deny a tool call"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/objectives/{path_param('objectiveId', objective_id)}/tool_calls/{path_param('toolCallId', tool_call_id)}:deny"
        _body = {
            "memo": memo,
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("POST", _path, body=_body, request_options=request_options)
        return decode_response("objectives.deny_tool_call", _data, lambda _d: types.ObjectiveToolCall._from_json(_d))

    def set_tool_call_content(
        self,
        objective_id: str,
        tool_call_id: str,
        *,
        content: List[types.SetToolCallContentRequest_ContentBlockParam],
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.ObjectiveToolCall:
        """Set a bare tool call's content"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/objectives/{path_param('objectiveId', objective_id)}/tool_calls/{path_param('toolCallId', tool_call_id)}:setContent"
        _body = {
            "content": (lambda _v: [((lambda _v: types._encode_SetToolCallContentRequest_ContentBlock(_v)))(_i) for _i in _v] if isinstance(_v, list) else _v)(content),
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("POST", _path, body=_body, request_options=request_options)
        return decode_response("objectives.set_tool_call_content", _data, lambda _d: types.ObjectiveToolCall._from_json(_d))

    def list_tools(
        self,
        objective_id: str,
        *,
        workspace_id: Optional[str] = None,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[types.ObjectiveTool]:
        """List objective tools"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/objectives/{path_param('objectiveId', objective_id)}/tools"
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options) or {}
        _items = decode_response("objectives.list_tools", _data, lambda _d: [types.ObjectiveTool._from_json(item) for item in (_d.get("items") or [])])
        _next_cursor = (((_data).get("pagination") or {})).get("nextCursor") or ""

        def _fetch(_cursor: str) -> SyncPage[types.ObjectiveTool]:
            return self.list_tools(objective_id, workspace_id=workspace_id, limit=limit, cursor=_cursor, request_options=request_options)

        return SyncPage(_items, _next_cursor, _fetch)

    def cancel(
        self,
        objective_id: str,
        *,
        workspace_id: Optional[str] = None,
        reason: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.Objective:
        """Cancel an objective"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/objectives/{path_param('objectiveId', objective_id)}:cancel"
        _body = {
            "reason": reason,
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("POST", _path, body=_body, request_options=request_options)
        return decode_response("objectives.cancel", _data, lambda _d: types.Objective._from_json(_d))

    def compact(
        self,
        objective_id: str,
        *,
        workspace_id: Optional[str] = None,
        compaction_config: Optional[types.AgentVariationSpec_CompactionConfigParam] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.CompactObjectiveResponse:
        """Compact an objective"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/objectives/{path_param('objectiveId', objective_id)}:compact"
        _body = {
            "compactionConfig": (lambda _v: types._encode_AgentVariationSpec_CompactionConfig(_v))(compaction_config),
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("POST", _path, body=_body, request_options=request_options)
        return decode_response("objectives.compact", _data, lambda _d: types.CompactObjectiveResponse._from_json(_d))

    def continue_(
        self,
        objective_id: str,
        *,
        message: str,
        workspace_id: Optional[str] = None,
        enqueue: Optional[bool] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.ObjectiveEvent:
        """Continue an objective"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/objectives/{path_param('objectiveId', objective_id)}:continue"
        _body = {
            "message": message,
            "enqueue": enqueue,
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("POST", _path, body=_body, request_options=request_options)
        return decode_response("objectives.continue_", _data, lambda _d: types.ObjectiveEvent._from_json(_d))
