# Code generated by redwood. DO NOT EDIT.
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional, Union

from .. import types
from .._core import Core, RequestOptions, decode_response, parse_datetime, path_param
from .._pagination import SyncPage
from .._sse import Stream


class Profiles:
    def __init__(self, core: Core) -> None:
        self._core = core

    def whoami(
        self,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> types.Profile:
        """Retrieves the profile for the credentials accessing the API"""
        _path = "/v1/whoami"
        _data = self._core.request("GET", _path, request_options=request_options)
        return decode_response("profiles.whoami", _data, lambda _d: types.Profile._from_json(_d))
