# Code generated by redwood. DO NOT EDIT.
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional, Union

from .. import types
from .._core import Core, RequestOptions, decode_response, parse_datetime, path_param
from .._pagination import SyncPage
from .._sse import Stream


class Tools:
    def __init__(self, core: Core) -> None:
        self._core = core

    def list(
        self,
        tool_set_id: str,
        *,
        workspace_id: Optional[str] = None,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        prefix: Optional[str] = None,
        query: Optional[str] = None,
        names: Optional[List[str]] = None,
        states: Optional[List[types.ToolServiceListToolsStates]] = None,
        requires_approval: Optional[bool] = None,
        labels: Optional[str] = None,
        sort_order: Optional[str] = None,
        include_info: Optional[bool] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[types.Tool]:
        """List tools"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/tool_sets/{path_param('toolSetId', tool_set_id)}/tools"
        names = list(names) if names is not None else None
        states = list(states) if states is not None else None
        _query = {
            "limit": limit,
            "cursor": cursor,
            "prefix": prefix,
            "query": query,
            "names": names,
            "states": states,
            "requiresApproval": requires_approval,
            "labels": labels,
            "sortOrder": sort_order,
            "includeInfo": include_info,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options) or {}
        _items = decode_response("tool_sets.tools.list", _data, lambda _d: [types.Tool._from_json(item) for item in (_d.get("items") or [])])
        _next_cursor = (((_data).get("pagination") or {})).get("nextCursor") or ""

        def _fetch(_cursor: str) -> SyncPage[types.Tool]:
            return self.list(tool_set_id, workspace_id=workspace_id, limit=limit, cursor=_cursor, prefix=prefix, query=query, names=names, states=states, requires_approval=requires_approval, labels=labels, sort_order=sort_order, include_info=include_info, request_options=request_options)

        return SyncPage(_items, _next_cursor, _fetch)

    def create(
        self,
        tool_set_id: str,
        *,
        metadata: types.CreateResourceMetadataParam,
        spec: types.ToolSpecParam,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.Tool:
        """Create a new tool"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/tool_sets/{path_param('toolSetId', tool_set_id)}/tools"
        _body = {
            "metadata": (lambda _v: types._encode_CreateResourceMetadata(_v))(metadata),
            "spec": (lambda _v: types._encode_ToolSpec(_v))(spec),
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("POST", _path, body=_body, request_options=request_options)
        return decode_response("tool_sets.tools.create", _data, lambda _d: types.Tool._from_json(_d))

    def retrieve(
        self,
        tool_set_id: str,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.Tool:
        """Get a tool by ID"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/tool_sets/{path_param('toolSetId', tool_set_id)}/tools/{path_param('id', id)}"
        _data = self._core.request("GET", _path, request_options=request_options)
        return decode_response("tool_sets.tools.retrieve", _data, lambda _d: types.Tool._from_json(_d))

    def delete(
        self,
        tool_set_id: str,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> None:
        """Delete a tool"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/tool_sets/{path_param('toolSetId', tool_set_id)}/tools/{path_param('id', id)}"
        self._core.request("DELETE", _path, expects_body=False, request_options=request_options)
        return None

    def update(
        self,
        tool_set_id: str,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        metadata: Optional[types.UpdateResourceMetadataParam] = None,
        spec: Optional[types.ToolSpecParam] = None,
        update_mask: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.Tool:
        """Update a tool"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/tool_sets/{path_param('toolSetId', tool_set_id)}/tools/{path_param('id', id)}"
        _body = {
            "metadata": (lambda _v: types._encode_UpdateResourceMetadata(_v))(metadata),
            "spec": (lambda _v: types._encode_ToolSpec(_v))(spec),
            "updateMask": update_mask,
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("PATCH", _path, body=_body, request_options=request_options)
        return decode_response("tool_sets.tools.update", _data, lambda _d: types.Tool._from_json(_d))

    def omit(
        self,
        tool_set_id: str,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.Tool:
        """Omit a tool"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/tool_sets/{path_param('toolSetId', tool_set_id)}/tools/{path_param('id', id)}:omit"
        _data = self._core.request("POST", _path, request_options=request_options)
        return decode_response("tool_sets.tools.omit", _data, lambda _d: types.Tool._from_json(_d))

    def restore(
        self,
        tool_set_id: str,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.Tool:
        """Restore a tool"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/tool_sets/{path_param('toolSetId', tool_set_id)}/tools/{path_param('id', id)}:restore"
        _data = self._core.request("POST", _path, request_options=request_options)
        return decode_response("tool_sets.tools.restore", _data, lambda _d: types.Tool._from_json(_d))
