# Code generated by redwood. DO NOT EDIT.
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional, Union

from .. import types
from .._core import Core, RequestOptions, decode_response, parse_datetime, path_param
from .._pagination import SyncPage
from .._sse import Stream


from .tool_set_secrets import ToolSetSecrets
from .tools import Tools

class ToolSets:
    def __init__(self, core: Core) -> None:
        self._core = core
        self.secrets = ToolSetSecrets(core)
        self.tools = Tools(core)

    def list(
        self,
        *,
        workspace_id: Optional[str] = None,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        prefix: Optional[str] = None,
        query: Optional[str] = None,
        state: Optional[types.ToolServiceListToolSetsState] = None,
        labels: Optional[str] = None,
        sort_order: Optional[str] = None,
        include_info: Optional[bool] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[types.ToolSet]:
        """List tool sets"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/tool_sets"
        _query = {
            "limit": limit,
            "cursor": cursor,
            "prefix": prefix,
            "query": query,
            "state": state,
            "labels": labels,
            "sortOrder": sort_order,
            "includeInfo": include_info,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options) or {}
        _items = decode_response("tool_sets.list", _data, lambda _d: [types.ToolSet._from_json(item) for item in (_d.get("items") or [])])
        _next_cursor = (((_data).get("pagination") or {})).get("nextCursor") or ""

        def _fetch(_cursor: str) -> SyncPage[types.ToolSet]:
            return self.list(workspace_id=workspace_id, limit=limit, cursor=_cursor, prefix=prefix, query=query, state=state, labels=labels, sort_order=sort_order, include_info=include_info, request_options=request_options)

        return SyncPage(_items, _next_cursor, _fetch)

    def create(
        self,
        *,
        metadata: types.CreateResourceMetadataParam,
        spec: types.ToolSetSpecParam,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.ToolSet:
        """Create a new tool set"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/tool_sets"
        _body = {
            "metadata": (lambda _v: types._encode_CreateResourceMetadata(_v))(metadata),
            "spec": (lambda _v: types._encode_ToolSetSpec(_v))(spec),
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("POST", _path, body=_body, request_options=request_options)
        return decode_response("tool_sets.create", _data, lambda _d: types.ToolSet._from_json(_d))

    def retrieve(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.ToolSet:
        """Get a tool set by ID"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/tool_sets/{path_param('id', id)}"
        _data = self._core.request("GET", _path, request_options=request_options)
        return decode_response("tool_sets.retrieve", _data, lambda _d: types.ToolSet._from_json(_d))

    def delete(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> None:
        """Delete a tool set"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/tool_sets/{path_param('id', id)}"
        self._core.request("DELETE", _path, expects_body=False, request_options=request_options)
        return None

    def update(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        metadata: Optional[types.UpdateResourceMetadataParam] = None,
        spec: Optional[types.ToolSetSpecParam] = None,
        update_mask: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.ToolSet:
        """Update a tool set"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/tool_sets/{path_param('id', id)}"
        _body = {
            "metadata": (lambda _v: types._encode_UpdateResourceMetadata(_v))(metadata),
            "spec": (lambda _v: types._encode_ToolSetSpec(_v))(spec),
            "updateMask": update_mask,
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("PATCH", _path, body=_body, request_options=request_options)
        return decode_response("tool_sets.update", _data, lambda _d: types.ToolSet._from_json(_d))

    def archive(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.ToolSet:
        """Archive a tool set"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/tool_sets/{path_param('id', id)}:archive"
        _data = self._core.request("POST", _path, request_options=request_options)
        return decode_response("tool_sets.archive", _data, lambda _d: types.ToolSet._from_json(_d))

    def unarchive(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.ToolSet:
        """Unarchive a tool set"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/tool_sets/{path_param('id', id)}:unarchive"
        _data = self._core.request("POST", _path, request_options=request_options)
        return decode_response("tool_sets.unarchive", _data, lambda _d: types.ToolSet._from_json(_d))

    def list_events(
        self,
        tool_set_id: str,
        *,
        workspace_id: Optional[str] = None,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        sort_order: Optional[str] = None,
        include_info: Optional[bool] = None,
        labels: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[types.ToolSetEvent]:
        """List tool set events"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/tool_sets/{path_param('toolSetId', tool_set_id)}/events"
        _query = {
            "limit": limit,
            "cursor": cursor,
            "sortOrder": sort_order,
            "includeInfo": include_info,
            "labels": labels,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options) or {}
        _items = decode_response("tool_sets.list_events", _data, lambda _d: [types.ToolSetEvent._from_json(item) for item in (_d.get("items") or [])])
        _next_cursor = (((_data).get("pagination") or {})).get("nextCursor") or ""

        def _fetch(_cursor: str) -> SyncPage[types.ToolSetEvent]:
            return self.list_events(tool_set_id, workspace_id=workspace_id, limit=limit, cursor=_cursor, sort_order=sort_order, include_info=include_info, labels=labels, request_options=request_options)

        return SyncPage(_items, _next_cursor, _fetch)

    def retrieve_open_api_spec(
        self,
        tool_set_id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.GetToolSetOpenAPISpecResponse:
        """Get consumed OpenAPI spec"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/tool_sets/{path_param('toolSetId', tool_set_id)}/openapi_spec"
        _data = self._core.request("GET", _path, request_options=request_options)
        return decode_response("tool_sets.retrieve_open_api_spec", _data, lambda _d: types.GetToolSetOpenAPISpecResponse._from_json(_d))

    def list_usage(
        self,
        tool_set_id: str,
        *,
        workspace_id: Optional[str] = None,
        tool_id: Optional[str] = None,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        sort_order: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[types.ToolSetUsage]:
        """List tool set usage"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/tool_sets/{path_param('toolSetId', tool_set_id)}/usage"
        _query = {
            "toolId": tool_id,
            "limit": limit,
            "cursor": cursor,
            "sortOrder": sort_order,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options) or {}
        _items = decode_response("tool_sets.list_usage", _data, lambda _d: [types.ToolSetUsage._from_json(item) for item in (_d.get("items") or [])])
        _next_cursor = (((_data).get("pagination") or {})).get("nextCursor") or ""

        def _fetch(_cursor: str) -> SyncPage[types.ToolSetUsage]:
            return self.list_usage(tool_set_id, workspace_id=workspace_id, tool_id=tool_id, limit=limit, cursor=_cursor, sort_order=sort_order, request_options=request_options)

        return SyncPage(_items, _next_cursor, _fetch)
