# Code generated by redwood. DO NOT EDIT.
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional, Union

from .. import types
from .._core import Core, RequestOptions, decode_response, parse_datetime, path_param
from .._pagination import SyncPage
from .._sse import Stream


class ToolSearch:
    def __init__(self, core: Core) -> None:
        self._core = core

    def search_or_sets(
        self,
        *,
        query: str,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.SearchToolsOrToolSetsResponse:
        """Search for tools or tool sets"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/search/tools_or_tool_sets"
        _query = {
            "query": query,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options)
        return decode_response("tool_search.search_or_sets", _data, lambda _d: types.SearchToolsOrToolSetsResponse._from_json(_d))
