# Code generated by redwood. DO NOT EDIT.
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional, Union

from .. import types
from .._core import Core, RequestOptions, decode_response, parse_datetime, path_param
from .._pagination import SyncPage
from .._sse import Stream


class WidgetSessions:
    def __init__(self, core: Core) -> None:
        self._core = core

    def list(
        self,
        *,
        workspace_id: Optional[str] = None,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        widget_id: Optional[str] = None,
        tenant_id: Optional[str] = None,
        subject_id: Optional[str] = None,
        state: Optional[types.WidgetSessionServiceListWidgetSessionsState] = None,
        labels: Optional[str] = None,
        sort_order: Optional[str] = None,
        include_info: Optional[bool] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[types.WidgetSession]:
        """List widget sessions"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/widget_sessions"
        _query = {
            "limit": limit,
            "cursor": cursor,
            "widgetId": widget_id,
            "tenantId": tenant_id,
            "subjectId": subject_id,
            "state": state,
            "labels": labels,
            "sortOrder": sort_order,
            "includeInfo": include_info,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options) or {}
        _items = decode_response("widget_sessions.list", _data, lambda _d: [types.WidgetSession._from_json(item) for item in (_d.get("items") or [])])
        _next_cursor = (((_data).get("pagination") or {})).get("nextCursor") or ""

        def _fetch(_cursor: str) -> SyncPage[types.WidgetSession]:
            return self.list(workspace_id=workspace_id, limit=limit, cursor=_cursor, widget_id=widget_id, tenant_id=tenant_id, subject_id=subject_id, state=state, labels=labels, sort_order=sort_order, include_info=include_info, request_options=request_options)

        return SyncPage(_items, _next_cursor, _fetch)

    def create(
        self,
        *,
        spec: types.WidgetSessionSpecParam,
        workspace_id: Optional[str] = None,
        metadata: Optional[types.CreateOperationMetadataParam] = None,
        secrets: Optional[List[types.CreateWidgetSessionRequest_SecretParam]] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.WidgetSession:
        """Create a widget session"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/widget_sessions"
        _body = {
            "metadata": (lambda _v: types._encode_CreateOperationMetadata(_v))(metadata),
            "spec": (lambda _v: types._encode_WidgetSessionSpec(_v))(spec),
            "secrets": (lambda _v: [((lambda _v: types._encode_CreateWidgetSessionRequest_Secret(_v)))(_i) for _i in _v] if isinstance(_v, list) else _v)(secrets),
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("POST", _path, body=_body, request_options=request_options)
        return decode_response("widget_sessions.create", _data, lambda _d: types.WidgetSession._from_json(_d))

    def delete_tenant(
        self,
        *,
        workspace_id: Optional[str] = None,
        tenant_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.DeleteTenantWidgetSessionsResponse:
        """Delete all of a tenant's widget sessions"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/widget_sessions"
        _query = {
            "tenantId": tenant_id,
        }
        _data = self._core.request("DELETE", _path, query=_query, request_options=request_options)
        return decode_response("widget_sessions.delete_tenant", _data, lambda _d: types.DeleteTenantWidgetSessionsResponse._from_json(_d))

    def retrieve(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.WidgetSession:
        """Get a widget session by ID"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/widget_sessions/{path_param('id', id)}"
        _data = self._core.request("GET", _path, request_options=request_options)
        return decode_response("widget_sessions.retrieve", _data, lambda _d: types.WidgetSession._from_json(_d))

    def delete(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> None:
        """Delete a widget session"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/widget_sessions/{path_param('id', id)}"
        self._core.request("DELETE", _path, expects_body=False, request_options=request_options)
        return None

    def revoke(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.WidgetSession:
        """Revoke a widget session"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/widget_sessions/{path_param('id', id)}:revoke"
        _data = self._core.request("POST", _path, request_options=request_options)
        return decode_response("widget_sessions.revoke", _data, lambda _d: types.WidgetSession._from_json(_d))
