# Code generated by redwood. DO NOT EDIT.
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional, Union

from .. import types
from .._core import Core, RequestOptions, decode_response, parse_datetime, path_param
from .._pagination import SyncPage
from .._sse import Stream


class Workspaces:
    def __init__(self, core: Core) -> None:
        self._core = core

    def list(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        sort_order: Optional[str] = None,
        include_info: Optional[bool] = None,
        labels: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[types.Workspace]:
        """List workspaces"""
        _path = "/v1/workspaces"
        _query = {
            "limit": limit,
            "cursor": cursor,
            "sortOrder": sort_order,
            "includeInfo": include_info,
            "labels": labels,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options) or {}
        _items = decode_response("workspaces.list", _data, lambda _d: [types.Workspace._from_json(item) for item in (_d.get("items") or [])])
        _next_cursor = (((_data).get("pagination") or {})).get("nextCursor") or ""

        def _fetch(_cursor: str) -> SyncPage[types.Workspace]:
            return self.list(limit=limit, cursor=_cursor, sort_order=sort_order, include_info=include_info, labels=labels, request_options=request_options)

        return SyncPage(_items, _next_cursor, _fetch)
