# Code generated by redwood. DO NOT EDIT.
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional, Union

from .. import types
from .._core import Core, RequestOptions, decode_response, parse_datetime, path_param
from .._pagination import SyncPage
from .._sse import Stream


class WorkspaceAdmin:
    def __init__(self, core: Core) -> None:
        self._core = core

    def list_profiles(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        query: Optional[str] = None,
        labels: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[types.Profile]:
        """Search account profiles"""
        _path = "/v1/account/profiles"
        _query = {
            "limit": limit,
            "cursor": cursor,
            "query": query,
            "labels": labels,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options) or {}
        _items = decode_response("workspace_admin.list_profiles", _data, lambda _d: [types.Profile._from_json(item) for item in (_d.get("items") or [])])
        _next_cursor = (((_data).get("pagination") or {})).get("nextCursor") or ""

        def _fetch(_cursor: str) -> SyncPage[types.Profile]:
            return self.list_profiles(limit=limit, cursor=_cursor, query=query, labels=labels, request_options=request_options)

        return SyncPage(_items, _next_cursor, _fetch)

    def list_account(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        include_archived: Optional[bool] = None,
        labels: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[types.Workspace]:
        """List all workspaces in the account"""
        _path = "/v1/account/workspaces"
        _query = {
            "limit": limit,
            "cursor": cursor,
            "includeArchived": include_archived,
            "labels": labels,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options) or {}
        _items = decode_response("workspace_admin.list_account", _data, lambda _d: [types.Workspace._from_json(item) for item in (_d.get("items") or [])])
        _next_cursor = (((_data).get("pagination") or {})).get("nextCursor") or ""

        def _fetch(_cursor: str) -> SyncPage[types.Workspace]:
            return self.list_account(limit=limit, cursor=_cursor, include_archived=include_archived, labels=labels, request_options=request_options)

        return SyncPage(_items, _next_cursor, _fetch)

    def create(
        self,
        *,
        metadata: types.CreateAccountResourceMetadataParam,
        spec: types.WorkspaceSpecParam,
        request_options: Optional[RequestOptions] = None,
    ) -> types.Workspace:
        """Create a workspace"""
        _path = "/v1/account/workspaces"
        _body = {
            "metadata": (lambda _v: types._encode_CreateAccountResourceMetadata(_v))(metadata),
            "spec": (lambda _v: types._encode_WorkspaceSpec(_v))(spec),
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("POST", _path, body=_body, request_options=request_options)
        return decode_response("workspace_admin.create", _data, lambda _d: types.Workspace._from_json(_d))

    def retrieve(
        self,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.Workspace:
        """Get a workspace by ID"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/account/workspaces/{path_param('workspaceId', workspace_id)}"
        _data = self._core.request("GET", _path, request_options=request_options)
        return decode_response("workspace_admin.retrieve", _data, lambda _d: types.Workspace._from_json(_d))

    def archive(
        self,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> None:
        """Archive a workspace"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/account/workspaces/{path_param('workspaceId', workspace_id)}"
        self._core.request("DELETE", _path, expects_body=False, request_options=request_options)
        return None

    def update(
        self,
        *,
        workspace_id: Optional[str] = None,
        metadata: Optional[types.UpdateAccountResourceMetadataParam] = None,
        spec: Optional[types.WorkspaceSpecParam] = None,
        update_mask: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.Workspace:
        """Update a workspace"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/account/workspaces/{path_param('workspaceId', workspace_id)}"
        _body = {
            "metadata": (lambda _v: types._encode_UpdateAccountResourceMetadata(_v))(metadata),
            "spec": (lambda _v: types._encode_WorkspaceSpec(_v))(spec),
            "updateMask": update_mask,
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("PATCH", _path, body=_body, request_options=request_options)
        return decode_response("workspace_admin.update", _data, lambda _d: types.Workspace._from_json(_d))

    def list_members(
        self,
        *,
        workspace_id: Optional[str] = None,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[types.WorkspaceMember]:
        """List workspace members"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/account/workspaces/{path_param('workspaceId', workspace_id)}/members"
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options) or {}
        _items = decode_response("workspace_admin.list_members", _data, lambda _d: [types.WorkspaceMember._from_json(item) for item in (_d.get("items") or [])])
        _next_cursor = (((_data).get("pagination") or {})).get("nextCursor") or ""

        def _fetch(_cursor: str) -> SyncPage[types.WorkspaceMember]:
            return self.list_members(workspace_id=workspace_id, limit=limit, cursor=_cursor, request_options=request_options)

        return SyncPage(_items, _next_cursor, _fetch)

    def add_member(
        self,
        *,
        workspace_id: Optional[str] = None,
        profile_id: Optional[str] = None,
        email: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.WorkspaceMember:
        """Add a member to a workspace"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/account/workspaces/{path_param('workspaceId', workspace_id)}/members"
        _body = {
            "profileId": profile_id,
            "email": email,
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("POST", _path, body=_body, request_options=request_options)
        return decode_response("workspace_admin.add_member", _data, lambda _d: types.WorkspaceMember._from_json(_d))

    def remove_member(
        self,
        profile_id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> None:
        """Remove a member from a workspace"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/account/workspaces/{path_param('workspaceId', workspace_id)}/members/{path_param('profileId', profile_id)}"
        self._core.request("DELETE", _path, expects_body=False, request_options=request_options)
        return None
