# Code generated by redwood. DO NOT EDIT.
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional, Union

from .. import types
from .._core import Core, RequestOptions, decode_response, parse_datetime, path_param
from .._pagination import SyncPage
from .._sse import Stream


class WorkspaceSecrets:
    def __init__(self, core: Core) -> None:
        self._core = core

    def list(
        self,
        *,
        workspace_id: Optional[str] = None,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        prefix: Optional[str] = None,
        query: Optional[str] = None,
        labels: Optional[str] = None,
        sort_order: Optional[str] = None,
        include_info: Optional[bool] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SyncPage[types.WorkspaceSecret]:
        """List workspace secrets"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/workspace_secrets"
        _query = {
            "limit": limit,
            "cursor": cursor,
            "prefix": prefix,
            "query": query,
            "labels": labels,
            "sortOrder": sort_order,
            "includeInfo": include_info,
        }
        _data = self._core.request("GET", _path, query=_query, request_options=request_options) or {}
        _items = decode_response("workspace_secrets.list", _data, lambda _d: [types.WorkspaceSecret._from_json(item) for item in (_d.get("items") or [])])
        _next_cursor = (((_data).get("pagination") or {})).get("nextCursor") or ""

        def _fetch(_cursor: str) -> SyncPage[types.WorkspaceSecret]:
            return self.list(workspace_id=workspace_id, limit=limit, cursor=_cursor, prefix=prefix, query=query, labels=labels, sort_order=sort_order, include_info=include_info, request_options=request_options)

        return SyncPage(_items, _next_cursor, _fetch)

    def create(
        self,
        *,
        metadata: types.CreateResourceMetadataParam,
        spec: types.WorkspaceSecretSpecParam,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.WorkspaceSecret:
        """Create a new workspace secret"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/workspace_secrets"
        _body = {
            "metadata": (lambda _v: types._encode_CreateResourceMetadata(_v))(metadata),
            "spec": (lambda _v: types._encode_WorkspaceSecretSpec(_v))(spec),
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("POST", _path, body=_body, request_options=request_options)
        return decode_response("workspace_secrets.create", _data, lambda _d: types.WorkspaceSecret._from_json(_d))

    def retrieve(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.WorkspaceSecret:
        """Get a workspace secret by ID"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/workspace_secrets/{path_param('id', id)}"
        _data = self._core.request("GET", _path, request_options=request_options)
        return decode_response("workspace_secrets.retrieve", _data, lambda _d: types.WorkspaceSecret._from_json(_d))

    def delete(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> None:
        """Delete a workspace secret"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/workspace_secrets/{path_param('id', id)}"
        self._core.request("DELETE", _path, expects_body=False, request_options=request_options)
        return None

    def update(
        self,
        id: str,
        *,
        workspace_id: Optional[str] = None,
        metadata: Optional[types.UpdateResourceMetadataParam] = None,
        spec: Optional[types.WorkspaceSecretSpecParam] = None,
        update_mask: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> types.WorkspaceSecret:
        """Update a workspace secret"""
        workspace_id = self._core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = f"/v1/workspaces/{path_param('workspaceId', workspace_id)}/workspace_secrets/{path_param('id', id)}"
        _body = {
            "metadata": (lambda _v: types._encode_UpdateResourceMetadata(_v))(metadata),
            "spec": (lambda _v: types._encode_WorkspaceSecretSpec(_v))(spec),
            "updateMask": update_mask,
        }
        _body = {_k: _v for _k, _v in _body.items() if _v is not None}
        _data = self._core.request("PATCH", _path, body=_body, request_options=request_options)
        return decode_response("workspace_secrets.update", _data, lambda _d: types.WorkspaceSecret._from_json(_d))
